{
 "title": "Todo List API",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total requests",
   "type": "stat",
   "description": "returns the number of requests made on each endpoint",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_received_total{endpoint=\"/contacts\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total POST Requests",
   "type": "stat",
   "description": "returns the number of requests made on post endpoint",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{endpoint=\"/contacts\", method=\"POST\", code=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total POST Failed",
   "type": "stat",
   "description": "returns the number of requests made on post endpoint",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{endpoint=\"/contacts\", method=\"POST\", code!=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Post Request Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{endpoint=\"/contacts\", method=\"POST\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total GET Requests",
   "type": "stat",
   "description": "returns the number of requests made on get endpoint",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{endpoint=\"/contacts\", method=\"GET\", code=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total GET Failed",
   "type": "stat",
   "description": "returns the number of requests made on get endpoint",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_received_total{instance=\"host.docker.internal:5019\", method=\"GET\", code!=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET Request Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{endpoint=\"/contacts\", method=\"GET\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Delete Requests",
   "type": "stat",
   "description": "returns the number of requests made on delete endpoint",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{endpoint=\"/contacts\", method=\"DELETE\", code=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Delete Failed",
   "type": "stat",
   "description": "returns the number of requests made on delete endpoint",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{endpoint=\"/contacts\", method=\"DELETE\", code!=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DELETE Request Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 20 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{endpoint=\"/contacts\", method=\"DELETE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total PUT Requests",
   "type": "stat",
   "description": "returns the number of requests made on put endpoint",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{endpoint=\"/contacts\", method=\"PUT\", code=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUT Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{endpoint=\"/contacts\", method=\"PUT\", code!=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUT Request Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 26 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{endpoint=\"/contacts\", method=\"PUT\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API CPU Usage",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "system_runtime_cpu_usage{job=\"api\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}